# Generated by Django 2.2.5 on 2022-01-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('var', models.CharField(max_length=20, verbose_name='var')),
                ('file', models.CharField(max_length=20, verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='key')),
                ('tone', models.CharField(max_length=10, verbose_name='tone')),
                ('keybordKey', models.CharField(max_length=10, verbose_name='keybordKey')),
                ('defaultPitch', models.IntegerField(verbose_name='defaultPitch')),
                ('position', models.CharField(max_length=10, verbose_name='position')),
                ('positionPX', models.CharField(max_length=10, verbose_name='positionPX')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.IntegerField(verbose_name='pitch')),
                ('duration', models.CharField(max_length=10, verbose_name='duration')),
                ('idKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnjoyMusic.Keys', verbose_name='idKey')),
                ('idSong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnjoyMusic.Songs', verbose_name='idSong')),
            ],
        ),
    ]
